### ISSUE TITLE
Allow users to claim their previous orders upon creating an account.

### ISSUE THREAD

**Issue by harrislapiroff** [littleweaver/django-brambling#246] opened 2014-10-28 17:32 UTC
Someone should be able to find their registration records on the site regardless of whether they originally registered with a Dancerfly account or can find the original receipt. I haven't actually looked at the new registration system yet, so I don't know whether or not this is already feasible. Just making a ticket so I don't forget.

**Comment by melinath** [comment] 2015-01-06 02:35
Then this is (I believe) a duplicate of #23.

**Comment by melinath** [comment] 2015-03-12 00:02
Closing as a duplicate.

**Comment by melinath** [comment] 2015-03-12 00:03
Re-openint because it's not. :-p

**Comment by melinath** [comment] 2015-04-28 21:24
I think it would make the most sense to handle this by having a view where folks can opt to take on old orders. Confirming your email would take you there, but we'd need another path as well, in case someone skipped it at first but wanted to change their mind later.

**Closed** 2015-09-16 19:00 UTC
Labels: enhancement
