### ISSUE TITLE
Availability Dates of Duplicate Event

### ISSUE THREAD

**Issue by harrislapiroff** [littleweaver/django-brambling#814] opened 2016-06-12 04:21 UTC
Updating lots of availability dates for item options of an event is highly irritating. This especially is an issue when duplicating an event for a new year, but all the availability dates for items are still set to the previous year. I can imagine a few possible ways to resolve this:

1. Resolve #550 
2. Allow the possibility of specifying availability dates in relative terms (i.e., "Two months before the event until the date of the event")
3. When duplicating an event, ask for the date of the event before duplicating items, and then automatically move all availability dates that much further into the future

**Comment by melinath** [comment] 2016-06-13 15:48
Duplicate of #521

**Comment by harrislapiroff** [comment] 2016-06-13 15:49
oops

**Closed by melinath** 2016-06-13 15:48 UTC
