### ISSUE TITLE
Easy way for organizers to email attendees

### ISSUE THREAD

**Issue by nmorduch** [littleweaver/django-brambling#617] opened 2015-09-13 00:23 UTC
This could be a button that copies an email list to your clipboard (too easy to forget to bcc)
or, better, it could be a way to send plain-text emails through us (also a good way to remind people we exist!)

OR we could have a mailto link that automatically has everyone in the bcc field??????

**Comment by melinath** [comment] 2015-09-16 00:19
Duplicate of #244

**Closed by melinath** 2015-09-16 00:19 UTC
