### ISSUE TITLE
Negative item availability counts

### ISSUE THREAD

**Issue by harrislapiroff** [littleweaver/django-brambling#871] opened 2017-06-07 18:48 UTC
This probably shouldn't be possible:

![screen shot 2017-06-07 at 2 47 18 pm](https://user-images.githubusercontent.com/296631/26895676-53636fe2-4b90-11e7-83b0-a5f158da168e.png)

**Comment by melinath** [comment] 2017-06-07 18:52
Closing as duplicate of #843

**Comment by harrislapiroff** [comment] 2017-06-07 18:52
JK #843 covers this--- dammit @melinath is too fast for me.

**Closed by melinath** 2017-06-07 18:52 UTC
Labels: bug
