### ISSUE TITLE
Add support for stripe refund via webhook

### ISSUE THREAD

**Issue by melinath** [littleweaver/django-brambling#380] opened 2015-03-01 18:46 UTC
Refunds of stripe charges can happen directly from their website. We should get notification via webhook and synchronize our data.

**Comment by harrislapiroff** [comment] 2015-08-12 19:08
Bumping this as important.

**Comment by harrislapiroff** [comment] 2015-08-12 19:09
We already have events that are issuing refunds via Stripe, so our financial data is already out of sync.

**Comment by melinath** [comment] 2015-08-12 19:11
Erp.

**Comment by harrislapiroff** [comment] 2015-09-17 00:42
Bumping again because this was last commented on over a month ago and is pretty important. :stuck_out_tongue_closed_eyes:

**Comment by harrislapiroff** [comment] 2016-05-02 15:44
Bumping again because more events are encountering this. :)

**Comment by melinath** [comment] 2016-05-02 15:50
I guess that at a minimum we should at least record the refund amount. That is definitely doable. Though it won't solve the problem of what's in the cart. That would be a separate problem.

**Comment by harrislapiroff** [comment] 2016-05-02 15:51
I actually think in a case like this it makes most sense to leave the cart as is. I think that would be expected behavior. Though I realize that might make refunding items later on a bit wonky...

**Comment by melinath** [comment] 2016-05-02 15:51
Yes, we wouldn't want to automatically change the cart.

**Comment by harrislapiroff** [comment] 2016-05-02 15:53
Ugh, although, a lot of times the reason to do this is to refund a pass minus a refund fee, so that would still leave an organizer's database messed up unless we offered a way to remove items from people _without_ refunding them. That way it could be two separate steps. 1. remove items; 2. issue partial refund (either through Stripe or through Dancerfly once #157 is resolved.

**Comment by melinath** [comment] 2016-05-02 15:55
Refunding through Dancerfly should definitely include selecting items to refund. That should be the preferred method of refunding. We should also *support* the webhook, but additional functionality for editing carts without a refund should be separate.

**Comment by harrislapiroff** [comment] 2016-05-02 16:08
I'm not sure that's true. I think refunding should _possibly_ include selecting items to refund, but I think it should also be possible to refund an arbitrary amount. To reiterate, many dance weekends have a policy of refunding all but a certain amount (i.e., refund all but $10) for cancellations. I don't think we should _force_ organizers to the Stripe dashboard to handle that. Especially since (and this is a separate, but also salient issue) the organizers of a specific event don't necessarily have access to their organization's payment processors.

**Comment by harrislapiroff** [comment] 2016-05-02 16:25
Moving this conversation to #157

**Closed** 2018-01-11 00:03 UTC
Labels: high priority
