### ISSUE TITLE
Allow registering as a partnership

### ISSUE THREAD

**Issue by j-po** [littleweaver/django-brambling#548] opened 2015-06-20 19:22 UTC
We'd like to offer a discount to partnerships registering together (to encourage role balance), and it'd be cool to be able to use the same reg form for both, plus email receipts and updates and stuff to both. Probably don't want to have to create an account for the second person at that point, though.

**Comment by melinath** [comment] 2015-06-20 20:07
This is a duplicate of #349 (essentially).

Also, just to clarify, account creation is not required for registration in any case.

**Closed by melinath** 2015-06-20 20:07 UTC
