### ISSUE TITLE
User unable to clear items from cart

### ISSUE THREAD

**Issue by micheleleah** [littleweaver/django-brambling#826] opened 2016-10-27 21:18 UTC
Multiple tickets show up in the user's cart when the user intended to purchase one ticket and the "red x" does not show up to allow the user to delete the extra ticket.

**Comment by raq929** [comment] 2017-05-16 15:11
I can't reproduce this error or find the original tickets with this problem. 
I tried it in Chrome, Safari & Firefox but was unable to get the error.

**Comment by melinath** [comment] 2017-05-16 15:27
Closing since we can't reproduce it.

**Closed by melinath** 2017-05-16 15:27 UTC
Labels: high priority
